// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/go-github/v81/github"
	mock "github.com/stretchr/testify/mock"
)

// NewGitGetGithubI creates a new instance of GitGetGithubI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitGetGithubI(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitGetGithubI {
	mock := &GitGetGithubI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitGetGithubI is an autogenerated mock type for the GitGetGithubI type
type GitGetGithubI struct {
	mock.Mock
}

type GitGetGithubI_Expecter struct {
	mock *mock.Mock
}

func (_m *GitGetGithubI) EXPECT() *GitGetGithubI_Expecter {
	return &GitGetGithubI_Expecter{mock: &_m.Mock}
}

// CreateRepository provides a mock function for the type GitGetGithubI
func (_mock *GitGetGithubI) CreateRepository(ctx context.Context, repositorySha string, repository string, mirrorVisibilityMode string, sourceURL string) *github.Repository {
	ret := _mock.Called(ctx, repositorySha, repository, mirrorVisibilityMode, sourceURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepository")
	}

	var r0 *github.Repository
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *github.Repository); ok {
		r0 = returnFunc(ctx, repositorySha, repository, mirrorVisibilityMode, sourceURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*github.Repository)
		}
	}
	return r0
}

// GitGetGithubI_CreateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepository'
type GitGetGithubI_CreateRepository_Call struct {
	*mock.Call
}

// CreateRepository is a helper method to define mock.On call
//   - ctx context.Context
//   - repositorySha string
//   - repository string
//   - mirrorVisibilityMode string
//   - sourceURL string
func (_e *GitGetGithubI_Expecter) CreateRepository(ctx interface{}, repositorySha interface{}, repository interface{}, mirrorVisibilityMode interface{}, sourceURL interface{}) *GitGetGithubI_CreateRepository_Call {
	return &GitGetGithubI_CreateRepository_Call{Call: _e.mock.On("CreateRepository", ctx, repositorySha, repository, mirrorVisibilityMode, sourceURL)}
}

func (_c *GitGetGithubI_CreateRepository_Call) Run(run func(ctx context.Context, repositorySha string, repository string, mirrorVisibilityMode string, sourceURL string)) *GitGetGithubI_CreateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *GitGetGithubI_CreateRepository_Call) Return(repository1 *github.Repository) *GitGetGithubI_CreateRepository_Call {
	_c.Call.Return(repository1)
	return _c
}

func (_c *GitGetGithubI_CreateRepository_Call) RunAndReturn(run func(ctx context.Context, repositorySha string, repository string, mirrorVisibilityMode string, sourceURL string) *github.Repository) *GitGetGithubI_CreateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOwnerRepos provides a mock function for the type GitGetGithubI
func (_mock *GitGetGithubI) FetchOwnerRepos(ctx context.Context, repoSha string, owner string, githubVisibility string, githubAffiliation string) []*github.Repository {
	ret := _mock.Called(ctx, repoSha, owner, githubVisibility, githubAffiliation)

	if len(ret) == 0 {
		panic("no return value specified for FetchOwnerRepos")
	}

	var r0 []*github.Repository
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) []*github.Repository); ok {
		r0 = returnFunc(ctx, repoSha, owner, githubVisibility, githubAffiliation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*github.Repository)
		}
	}
	return r0
}

// GitGetGithubI_FetchOwnerRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOwnerRepos'
type GitGetGithubI_FetchOwnerRepos_Call struct {
	*mock.Call
}

// FetchOwnerRepos is a helper method to define mock.On call
//   - ctx context.Context
//   - repoSha string
//   - owner string
//   - githubVisibility string
//   - githubAffiliation string
func (_e *GitGetGithubI_Expecter) FetchOwnerRepos(ctx interface{}, repoSha interface{}, owner interface{}, githubVisibility interface{}, githubAffiliation interface{}) *GitGetGithubI_FetchOwnerRepos_Call {
	return &GitGetGithubI_FetchOwnerRepos_Call{Call: _e.mock.On("FetchOwnerRepos", ctx, repoSha, owner, githubVisibility, githubAffiliation)}
}

func (_c *GitGetGithubI_FetchOwnerRepos_Call) Run(run func(ctx context.Context, repoSha string, owner string, githubVisibility string, githubAffiliation string)) *GitGetGithubI_FetchOwnerRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *GitGetGithubI_FetchOwnerRepos_Call) Return(repositorys []*github.Repository) *GitGetGithubI_FetchOwnerRepos_Call {
	_c.Call.Return(repositorys)
	return _c
}

func (_c *GitGetGithubI_FetchOwnerRepos_Call) RunAndReturn(run func(ctx context.Context, repoSha string, owner string, githubVisibility string, githubAffiliation string) []*github.Repository) *GitGetGithubI_FetchOwnerRepos_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type GitGetGithubI
func (_mock *GitGetGithubI) Init() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetGithubI_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type GitGetGithubI_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *GitGetGithubI_Expecter) Init() *GitGetGithubI_Init_Call {
	return &GitGetGithubI_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *GitGetGithubI_Init_Call) Run(run func()) *GitGetGithubI_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitGetGithubI_Init_Call) Return(b bool) *GitGetGithubI_Init_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetGithubI_Init_Call) RunAndReturn(run func() bool) *GitGetGithubI_Init_Call {
	_c.Call.Return(run)
	return _c
}

// RepositoryExists provides a mock function for the type GitGetGithubI
func (_mock *GitGetGithubI) RepositoryExists(ctx context.Context, repositorySha string, owner string, repository string) bool {
	ret := _mock.Called(ctx, repositorySha, owner, repository)

	if len(ret) == 0 {
		panic("no return value specified for RepositoryExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) bool); ok {
		r0 = returnFunc(ctx, repositorySha, owner, repository)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetGithubI_RepositoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepositoryExists'
type GitGetGithubI_RepositoryExists_Call struct {
	*mock.Call
}

// RepositoryExists is a helper method to define mock.On call
//   - ctx context.Context
//   - repositorySha string
//   - owner string
//   - repository string
func (_e *GitGetGithubI_Expecter) RepositoryExists(ctx interface{}, repositorySha interface{}, owner interface{}, repository interface{}) *GitGetGithubI_RepositoryExists_Call {
	return &GitGetGithubI_RepositoryExists_Call{Call: _e.mock.On("RepositoryExists", ctx, repositorySha, owner, repository)}
}

func (_c *GitGetGithubI_RepositoryExists_Call) Run(run func(ctx context.Context, repositorySha string, owner string, repository string)) *GitGetGithubI_RepositoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *GitGetGithubI_RepositoryExists_Call) Return(b bool) *GitGetGithubI_RepositoryExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetGithubI_RepositoryExists_Call) RunAndReturn(run func(ctx context.Context, repositorySha string, owner string, repository string) bool) *GitGetGithubI_RepositoryExists_Call {
	_c.Call.Return(run)
	return _c
}
