// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.com/gitlab-org/api/client-go"
)

// NewGitGetGitlabI creates a new instance of GitGetGitlabI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitGetGitlabI(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitGetGitlabI {
	mock := &GitGetGitlabI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitGetGitlabI is an autogenerated mock type for the GitGetGitlabI type
type GitGetGitlabI struct {
	mock.Mock
}

type GitGetGitlabI_Expecter struct {
	mock *mock.Mock
}

func (_m *GitGetGitlabI) EXPECT() *GitGetGitlabI_Expecter {
	return &GitGetGitlabI_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) CreateProject(repositorySha string, baseUrl string, projectName string, namespaceID int64, mirrorVisibilityMode string, sourceURL string) *gitlab.Project {
	ret := _mock.Called(repositorySha, baseUrl, projectName, namespaceID, mirrorVisibilityMode, sourceURL)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *gitlab.Project
	if returnFunc, ok := ret.Get(0).(func(string, string, string, int64, string, string) *gitlab.Project); ok {
		r0 = returnFunc(repositorySha, baseUrl, projectName, namespaceID, mirrorVisibilityMode, sourceURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Project)
		}
	}
	return r0
}

// GitGetGitlabI_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type GitGetGitlabI_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - repositorySha string
//   - baseUrl string
//   - projectName string
//   - namespaceID int64
//   - mirrorVisibilityMode string
//   - sourceURL string
func (_e *GitGetGitlabI_Expecter) CreateProject(repositorySha interface{}, baseUrl interface{}, projectName interface{}, namespaceID interface{}, mirrorVisibilityMode interface{}, sourceURL interface{}) *GitGetGitlabI_CreateProject_Call {
	return &GitGetGitlabI_CreateProject_Call{Call: _e.mock.On("CreateProject", repositorySha, baseUrl, projectName, namespaceID, mirrorVisibilityMode, sourceURL)}
}

func (_c *GitGetGitlabI_CreateProject_Call) Run(run func(repositorySha string, baseUrl string, projectName string, namespaceID int64, mirrorVisibilityMode string, sourceURL string)) *GitGetGitlabI_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_CreateProject_Call) Return(project *gitlab.Project) *GitGetGitlabI_CreateProject_Call {
	_c.Call.Return(project)
	return _c
}

func (_c *GitGetGitlabI_CreateProject_Call) RunAndReturn(run func(repositorySha string, baseUrl string, projectName string, namespaceID int64, mirrorVisibilityMode string, sourceURL string) *gitlab.Project) *GitGetGitlabI_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOwnerRepos provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) FetchOwnerRepos(repositorySha string, baseURL string, groupName string, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string) []*gitlab.Project {
	ret := _mock.Called(repositorySha, baseURL, groupName, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)

	if len(ret) == 0 {
		panic("no return value specified for FetchOwnerRepos")
	}

	var r0 []*gitlab.Project
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool, string, string) []*gitlab.Project); ok {
		r0 = returnFunc(repositorySha, baseURL, groupName, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}
	return r0
}

// GitGetGitlabI_FetchOwnerRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOwnerRepos'
type GitGetGitlabI_FetchOwnerRepos_Call struct {
	*mock.Call
}

// FetchOwnerRepos is a helper method to define mock.On call
//   - repositorySha string
//   - baseURL string
//   - groupName string
//   - gitlabOwned bool
//   - gitlabVisibility string
//   - gitlabMinAccessLevel string
func (_e *GitGetGitlabI_Expecter) FetchOwnerRepos(repositorySha interface{}, baseURL interface{}, groupName interface{}, gitlabOwned interface{}, gitlabVisibility interface{}, gitlabMinAccessLevel interface{}) *GitGetGitlabI_FetchOwnerRepos_Call {
	return &GitGetGitlabI_FetchOwnerRepos_Call{Call: _e.mock.On("FetchOwnerRepos", repositorySha, baseURL, groupName, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)}
}

func (_c *GitGetGitlabI_FetchOwnerRepos_Call) Run(run func(repositorySha string, baseURL string, groupName string, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string)) *GitGetGitlabI_FetchOwnerRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_FetchOwnerRepos_Call) Return(projects []*gitlab.Project) *GitGetGitlabI_FetchOwnerRepos_Call {
	_c.Call.Return(projects)
	return _c
}

func (_c *GitGetGitlabI_FetchOwnerRepos_Call) RunAndReturn(run func(repositorySha string, baseURL string, groupName string, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string) []*gitlab.Project) *GitGetGitlabI_FetchOwnerRepos_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectNamespace provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) GetProjectNamespace(repositorySha string, baseUrl string, projectNameFullPath string) (*gitlab.Namespace, string) {
	ret := _mock.Called(repositorySha, baseUrl, projectNameFullPath)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectNamespace")
	}

	var r0 *gitlab.Namespace
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*gitlab.Namespace, string)); ok {
		return returnFunc(repositorySha, baseUrl, projectNameFullPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *gitlab.Namespace); ok {
		r0 = returnFunc(repositorySha, baseUrl, projectNameFullPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gitlab.Namespace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) string); ok {
		r1 = returnFunc(repositorySha, baseUrl, projectNameFullPath)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// GitGetGitlabI_GetProjectNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectNamespace'
type GitGetGitlabI_GetProjectNamespace_Call struct {
	*mock.Call
}

// GetProjectNamespace is a helper method to define mock.On call
//   - repositorySha string
//   - baseUrl string
//   - projectNameFullPath string
func (_e *GitGetGitlabI_Expecter) GetProjectNamespace(repositorySha interface{}, baseUrl interface{}, projectNameFullPath interface{}) *GitGetGitlabI_GetProjectNamespace_Call {
	return &GitGetGitlabI_GetProjectNamespace_Call{Call: _e.mock.On("GetProjectNamespace", repositorySha, baseUrl, projectNameFullPath)}
}

func (_c *GitGetGitlabI_GetProjectNamespace_Call) Run(run func(repositorySha string, baseUrl string, projectNameFullPath string)) *GitGetGitlabI_GetProjectNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_GetProjectNamespace_Call) Return(namespace *gitlab.Namespace, s string) *GitGetGitlabI_GetProjectNamespace_Call {
	_c.Call.Return(namespace, s)
	return _c
}

func (_c *GitGetGitlabI_GetProjectNamespace_Call) RunAndReturn(run func(repositorySha string, baseUrl string, projectNameFullPath string) (*gitlab.Namespace, string)) *GitGetGitlabI_GetProjectNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) Init() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetGitlabI_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type GitGetGitlabI_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *GitGetGitlabI_Expecter) Init() *GitGetGitlabI_Init_Call {
	return &GitGetGitlabI_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *GitGetGitlabI_Init_Call) Run(run func()) *GitGetGitlabI_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitGetGitlabI_Init_Call) Return(b bool) *GitGetGitlabI_Init_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetGitlabI_Init_Call) RunAndReturn(run func() bool) *GitGetGitlabI_Init_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectExists provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) ProjectExists(repositorySha string, baseUrl string, projectName string) bool {
	ret := _mock.Called(repositorySha, baseUrl, projectName)

	if len(ret) == 0 {
		panic("no return value specified for ProjectExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = returnFunc(repositorySha, baseUrl, projectName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetGitlabI_ProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectExists'
type GitGetGitlabI_ProjectExists_Call struct {
	*mock.Call
}

// ProjectExists is a helper method to define mock.On call
//   - repositorySha string
//   - baseUrl string
//   - projectName string
func (_e *GitGetGitlabI_Expecter) ProjectExists(repositorySha interface{}, baseUrl interface{}, projectName interface{}) *GitGetGitlabI_ProjectExists_Call {
	return &GitGetGitlabI_ProjectExists_Call{Call: _e.mock.On("ProjectExists", repositorySha, baseUrl, projectName)}
}

func (_c *GitGetGitlabI_ProjectExists_Call) Run(run func(repositorySha string, baseUrl string, projectName string)) *GitGetGitlabI_ProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_ProjectExists_Call) Return(b bool) *GitGetGitlabI_ProjectExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetGitlabI_ProjectExists_Call) RunAndReturn(run func(repositorySha string, baseUrl string, projectName string) bool) *GitGetGitlabI_ProjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// appendGroupsProjects provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) appendGroupsProjects(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string) []*gitlab.Project {
	ret := _mock.Called(repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility)

	if len(ret) == 0 {
		panic("no return value specified for appendGroupsProjects")
	}

	var r0 []*gitlab.Project
	if returnFunc, ok := ret.Get(0).(func(string, *gitlab.Client, int64, string, []*gitlab.Project, bool, string) []*gitlab.Project); ok {
		r0 = returnFunc(repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}
	return r0
}

// GitGetGitlabI_appendGroupsProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'appendGroupsProjects'
type GitGetGitlabI_appendGroupsProjects_Call struct {
	*mock.Call
}

// appendGroupsProjects is a helper method to define mock.On call
//   - repoSha string
//   - git *gitlab.Client
//   - groupID int64
//   - groupName string
//   - glRepoList []*gitlab.Project
//   - gitlabOwned bool
//   - gitlabVisibility string
func (_e *GitGetGitlabI_Expecter) appendGroupsProjects(repoSha interface{}, git interface{}, groupID interface{}, groupName interface{}, glRepoList interface{}, gitlabOwned interface{}, gitlabVisibility interface{}) *GitGetGitlabI_appendGroupsProjects_Call {
	return &GitGetGitlabI_appendGroupsProjects_Call{Call: _e.mock.On("appendGroupsProjects", repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility)}
}

func (_c *GitGetGitlabI_appendGroupsProjects_Call) Run(run func(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string)) *GitGetGitlabI_appendGroupsProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *gitlab.Client
		if args[1] != nil {
			arg1 = args[1].(*gitlab.Client)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*gitlab.Project
		if args[4] != nil {
			arg4 = args[4].([]*gitlab.Project)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_appendGroupsProjects_Call) Return(projects []*gitlab.Project) *GitGetGitlabI_appendGroupsProjects_Call {
	_c.Call.Return(projects)
	return _c
}

func (_c *GitGetGitlabI_appendGroupsProjects_Call) RunAndReturn(run func(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string) []*gitlab.Project) *GitGetGitlabI_appendGroupsProjects_Call {
	_c.Call.Return(run)
	return _c
}

// getGroupID provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) getGroupID(repoSha string, git *gitlab.Client, groupName string) (int64, string, error) {
	ret := _mock.Called(repoSha, git, groupName)

	if len(ret) == 0 {
		panic("no return value specified for getGroupID")
	}

	var r0 int64
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, *gitlab.Client, string) (int64, string, error)); ok {
		return returnFunc(repoSha, git, groupName)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *gitlab.Client, string) int64); ok {
		r0 = returnFunc(repoSha, git, groupName)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *gitlab.Client, string) string); ok {
		r1 = returnFunc(repoSha, git, groupName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(string, *gitlab.Client, string) error); ok {
		r2 = returnFunc(repoSha, git, groupName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// GitGetGitlabI_getGroupID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getGroupID'
type GitGetGitlabI_getGroupID_Call struct {
	*mock.Call
}

// getGroupID is a helper method to define mock.On call
//   - repoSha string
//   - git *gitlab.Client
//   - groupName string
func (_e *GitGetGitlabI_Expecter) getGroupID(repoSha interface{}, git interface{}, groupName interface{}) *GitGetGitlabI_getGroupID_Call {
	return &GitGetGitlabI_getGroupID_Call{Call: _e.mock.On("getGroupID", repoSha, git, groupName)}
}

func (_c *GitGetGitlabI_getGroupID_Call) Run(run func(repoSha string, git *gitlab.Client, groupName string)) *GitGetGitlabI_getGroupID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *gitlab.Client
		if args[1] != nil {
			arg1 = args[1].(*gitlab.Client)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_getGroupID_Call) Return(n int64, s string, err error) *GitGetGitlabI_getGroupID_Call {
	_c.Call.Return(n, s, err)
	return _c
}

func (_c *GitGetGitlabI_getGroupID_Call) RunAndReturn(run func(repoSha string, git *gitlab.Client, groupName string) (int64, string, error)) *GitGetGitlabI_getGroupID_Call {
	_c.Call.Return(run)
	return _c
}

// gitlabAuth provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) gitlabAuth(repositorySha string, baseUrl string) bool {
	ret := _mock.Called(repositorySha, baseUrl)

	if len(ret) == 0 {
		panic("no return value specified for gitlabAuth")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(repositorySha, baseUrl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetGitlabI_gitlabAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'gitlabAuth'
type GitGetGitlabI_gitlabAuth_Call struct {
	*mock.Call
}

// gitlabAuth is a helper method to define mock.On call
//   - repositorySha string
//   - baseUrl string
func (_e *GitGetGitlabI_Expecter) gitlabAuth(repositorySha interface{}, baseUrl interface{}) *GitGetGitlabI_gitlabAuth_Call {
	return &GitGetGitlabI_gitlabAuth_Call{Call: _e.mock.On("gitlabAuth", repositorySha, baseUrl)}
}

func (_c *GitGetGitlabI_gitlabAuth_Call) Run(run func(repositorySha string, baseUrl string)) *GitGetGitlabI_gitlabAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_gitlabAuth_Call) Return(b bool) *GitGetGitlabI_gitlabAuth_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetGitlabI_gitlabAuth_Call) RunAndReturn(run func(repositorySha string, baseUrl string) bool) *GitGetGitlabI_gitlabAuth_Call {
	_c.Call.Return(run)
	return _c
}

// processSubgroups provides a mock function for the type GitGetGitlabI
func (_mock *GitGetGitlabI) processSubgroups(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string) []*gitlab.Project {
	ret := _mock.Called(repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)

	if len(ret) == 0 {
		panic("no return value specified for processSubgroups")
	}

	var r0 []*gitlab.Project
	if returnFunc, ok := ret.Get(0).(func(string, *gitlab.Client, int64, string, []*gitlab.Project, bool, string, string) []*gitlab.Project); ok {
		r0 = returnFunc(repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*gitlab.Project)
		}
	}
	return r0
}

// GitGetGitlabI_processSubgroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'processSubgroups'
type GitGetGitlabI_processSubgroups_Call struct {
	*mock.Call
}

// processSubgroups is a helper method to define mock.On call
//   - repoSha string
//   - git *gitlab.Client
//   - groupID int64
//   - groupName string
//   - glRepoList []*gitlab.Project
//   - gitlabOwned bool
//   - gitlabVisibility string
//   - gitlabMinAccessLevel string
func (_e *GitGetGitlabI_Expecter) processSubgroups(repoSha interface{}, git interface{}, groupID interface{}, groupName interface{}, glRepoList interface{}, gitlabOwned interface{}, gitlabVisibility interface{}, gitlabMinAccessLevel interface{}) *GitGetGitlabI_processSubgroups_Call {
	return &GitGetGitlabI_processSubgroups_Call{Call: _e.mock.On("processSubgroups", repoSha, git, groupID, groupName, glRepoList, gitlabOwned, gitlabVisibility, gitlabMinAccessLevel)}
}

func (_c *GitGetGitlabI_processSubgroups_Call) Run(run func(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string)) *GitGetGitlabI_processSubgroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *gitlab.Client
		if args[1] != nil {
			arg1 = args[1].(*gitlab.Client)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []*gitlab.Project
		if args[4] != nil {
			arg4 = args[4].([]*gitlab.Project)
		}
		var arg5 bool
		if args[5] != nil {
			arg5 = args[5].(bool)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 string
		if args[7] != nil {
			arg7 = args[7].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *GitGetGitlabI_processSubgroups_Call) Return(projects []*gitlab.Project) *GitGetGitlabI_processSubgroups_Call {
	_c.Call.Return(projects)
	return _c
}

func (_c *GitGetGitlabI_processSubgroups_Call) RunAndReturn(run func(repoSha string, git *gitlab.Client, groupID int64, groupName string, glRepoList []*gitlab.Project, gitlabOwned bool, gitlabVisibility string, gitlabMinAccessLevel string) []*gitlab.Project) *GitGetGitlabI_processSubgroups_Call {
	_c.Call.Return(run)
	return _c
}
