// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ktrysmt/go-bitbucket"
	mock "github.com/stretchr/testify/mock"
)

// NewGitGetBitbucketI creates a new instance of GitGetBitbucketI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitGetBitbucketI(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitGetBitbucketI {
	mock := &GitGetBitbucketI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GitGetBitbucketI is an autogenerated mock type for the GitGetBitbucketI type
type GitGetBitbucketI struct {
	mock.Mock
}

type GitGetBitbucketI_Expecter struct {
	mock *mock.Mock
}

func (_m *GitGetBitbucketI) EXPECT() *GitGetBitbucketI_Expecter {
	return &GitGetBitbucketI_Expecter{mock: &_m.Mock}
}

// CreateRepository provides a mock function for the type GitGetBitbucketI
func (_mock *GitGetBitbucketI) CreateRepository(repoSha string, repository string, mirrorVisibilityMode string, sourceURL string, projectName string) *bitbucket.Repository {
	ret := _mock.Called(repoSha, repository, mirrorVisibilityMode, sourceURL, projectName)

	if len(ret) == 0 {
		panic("no return value specified for CreateRepository")
	}

	var r0 *bitbucket.Repository
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string) *bitbucket.Repository); ok {
		r0 = returnFunc(repoSha, repository, mirrorVisibilityMode, sourceURL, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bitbucket.Repository)
		}
	}
	return r0
}

// GitGetBitbucketI_CreateRepository_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRepository'
type GitGetBitbucketI_CreateRepository_Call struct {
	*mock.Call
}

// CreateRepository is a helper method to define mock.On call
//   - repoSha string
//   - repository string
//   - mirrorVisibilityMode string
//   - sourceURL string
//   - projectName string
func (_e *GitGetBitbucketI_Expecter) CreateRepository(repoSha interface{}, repository interface{}, mirrorVisibilityMode interface{}, sourceURL interface{}, projectName interface{}) *GitGetBitbucketI_CreateRepository_Call {
	return &GitGetBitbucketI_CreateRepository_Call{Call: _e.mock.On("CreateRepository", repoSha, repository, mirrorVisibilityMode, sourceURL, projectName)}
}

func (_c *GitGetBitbucketI_CreateRepository_Call) Run(run func(repoSha string, repository string, mirrorVisibilityMode string, sourceURL string, projectName string)) *GitGetBitbucketI_CreateRepository_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *GitGetBitbucketI_CreateRepository_Call) Return(repository1 *bitbucket.Repository) *GitGetBitbucketI_CreateRepository_Call {
	_c.Call.Return(repository1)
	return _c
}

func (_c *GitGetBitbucketI_CreateRepository_Call) RunAndReturn(run func(repoSha string, repository string, mirrorVisibilityMode string, sourceURL string, projectName string) *bitbucket.Repository) *GitGetBitbucketI_CreateRepository_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOwnerRepos provides a mock function for the type GitGetBitbucketI
func (_mock *GitGetBitbucketI) FetchOwnerRepos(repoSha string, owner string, bitbucketRole string) []bitbucket.Repository {
	ret := _mock.Called(repoSha, owner, bitbucketRole)

	if len(ret) == 0 {
		panic("no return value specified for FetchOwnerRepos")
	}

	var r0 []bitbucket.Repository
	if returnFunc, ok := ret.Get(0).(func(string, string, string) []bitbucket.Repository); ok {
		r0 = returnFunc(repoSha, owner, bitbucketRole)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]bitbucket.Repository)
		}
	}
	return r0
}

// GitGetBitbucketI_FetchOwnerRepos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOwnerRepos'
type GitGetBitbucketI_FetchOwnerRepos_Call struct {
	*mock.Call
}

// FetchOwnerRepos is a helper method to define mock.On call
//   - repoSha string
//   - owner string
//   - bitbucketRole string
func (_e *GitGetBitbucketI_Expecter) FetchOwnerRepos(repoSha interface{}, owner interface{}, bitbucketRole interface{}) *GitGetBitbucketI_FetchOwnerRepos_Call {
	return &GitGetBitbucketI_FetchOwnerRepos_Call{Call: _e.mock.On("FetchOwnerRepos", repoSha, owner, bitbucketRole)}
}

func (_c *GitGetBitbucketI_FetchOwnerRepos_Call) Run(run func(repoSha string, owner string, bitbucketRole string)) *GitGetBitbucketI_FetchOwnerRepos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitGetBitbucketI_FetchOwnerRepos_Call) Return(repositorys []bitbucket.Repository) *GitGetBitbucketI_FetchOwnerRepos_Call {
	_c.Call.Return(repositorys)
	return _c
}

func (_c *GitGetBitbucketI_FetchOwnerRepos_Call) RunAndReturn(run func(repoSha string, owner string, bitbucketRole string) []bitbucket.Repository) *GitGetBitbucketI_FetchOwnerRepos_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type GitGetBitbucketI
func (_mock *GitGetBitbucketI) Init() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetBitbucketI_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type GitGetBitbucketI_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *GitGetBitbucketI_Expecter) Init() *GitGetBitbucketI_Init_Call {
	return &GitGetBitbucketI_Init_Call{Call: _e.mock.On("Init")}
}

func (_c *GitGetBitbucketI_Init_Call) Run(run func()) *GitGetBitbucketI_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitGetBitbucketI_Init_Call) Return(b bool) *GitGetBitbucketI_Init_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetBitbucketI_Init_Call) RunAndReturn(run func() bool) *GitGetBitbucketI_Init_Call {
	_c.Call.Return(run)
	return _c
}

// RepositoryExists provides a mock function for the type GitGetBitbucketI
func (_mock *GitGetBitbucketI) RepositoryExists(repoSha string, owner string, repository string) bool {
	ret := _mock.Called(repoSha, owner, repository)

	if len(ret) == 0 {
		panic("no return value specified for RepositoryExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = returnFunc(repoSha, owner, repository)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// GitGetBitbucketI_RepositoryExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RepositoryExists'
type GitGetBitbucketI_RepositoryExists_Call struct {
	*mock.Call
}

// RepositoryExists is a helper method to define mock.On call
//   - repoSha string
//   - owner string
//   - repository string
func (_e *GitGetBitbucketI_Expecter) RepositoryExists(repoSha interface{}, owner interface{}, repository interface{}) *GitGetBitbucketI_RepositoryExists_Call {
	return &GitGetBitbucketI_RepositoryExists_Call{Call: _e.mock.On("RepositoryExists", repoSha, owner, repository)}
}

func (_c *GitGetBitbucketI_RepositoryExists_Call) Run(run func(repoSha string, owner string, repository string)) *GitGetBitbucketI_RepositoryExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *GitGetBitbucketI_RepositoryExists_Call) Return(b bool) *GitGetBitbucketI_RepositoryExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *GitGetBitbucketI_RepositoryExists_Call) RunAndReturn(run func(repoSha string, owner string, repository string) bool) *GitGetBitbucketI_RepositoryExists_Call {
	_c.Call.Return(run)
	return _c
}
