// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"bytes"
	"os/exec"

	mock "github.com/stretchr/testify/mock"
)

// NewShellRunnerI creates a new instance of ShellRunnerI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShellRunnerI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShellRunnerI {
	mock := &ShellRunnerI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ShellRunnerI is an autogenerated mock type for the ShellRunnerI type
type ShellRunnerI struct {
	mock.Mock
}

type ShellRunnerI_Expecter struct {
	mock *mock.Mock
}

func (_m *ShellRunnerI) EXPECT() *ShellRunnerI_Expecter {
	return &ShellRunnerI_Expecter{mock: &_m.Mock}
}

// ExecGitCommand provides a mock function for the type ShellRunnerI
func (_mock *ShellRunnerI) ExecGitCommand(args []string, stdoutb *bytes.Buffer, erroutb *bytes.Buffer, dir string) (*exec.Cmd, error) {
	ret := _mock.Called(args, stdoutb, erroutb, dir)

	if len(ret) == 0 {
		panic("no return value specified for ExecGitCommand")
	}

	var r0 *exec.Cmd
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, *bytes.Buffer, *bytes.Buffer, string) (*exec.Cmd, error)); ok {
		return returnFunc(args, stdoutb, erroutb, dir)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, *bytes.Buffer, *bytes.Buffer, string) *exec.Cmd); ok {
		r0 = returnFunc(args, stdoutb, erroutb, dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string, *bytes.Buffer, *bytes.Buffer, string) error); ok {
		r1 = returnFunc(args, stdoutb, erroutb, dir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ShellRunnerI_ExecGitCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecGitCommand'
type ShellRunnerI_ExecGitCommand_Call struct {
	*mock.Call
}

// ExecGitCommand is a helper method to define mock.On call
//   - args []string
//   - stdoutb *bytes.Buffer
//   - erroutb *bytes.Buffer
//   - dir string
func (_e *ShellRunnerI_Expecter) ExecGitCommand(args interface{}, stdoutb interface{}, erroutb interface{}, dir interface{}) *ShellRunnerI_ExecGitCommand_Call {
	return &ShellRunnerI_ExecGitCommand_Call{Call: _e.mock.On("ExecGitCommand", args, stdoutb, erroutb, dir)}
}

func (_c *ShellRunnerI_ExecGitCommand_Call) Run(run func(args []string, stdoutb *bytes.Buffer, erroutb *bytes.Buffer, dir string)) *ShellRunnerI_ExecGitCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 *bytes.Buffer
		if args[1] != nil {
			arg1 = args[1].(*bytes.Buffer)
		}
		var arg2 *bytes.Buffer
		if args[2] != nil {
			arg2 = args[2].(*bytes.Buffer)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ShellRunnerI_ExecGitCommand_Call) Return(cmd *exec.Cmd, err error) *ShellRunnerI_ExecGitCommand_Call {
	_c.Call.Return(cmd, err)
	return _c
}

func (_c *ShellRunnerI_ExecGitCommand_Call) RunAndReturn(run func(args []string, stdoutb *bytes.Buffer, erroutb *bytes.Buffer, dir string) (*exec.Cmd, error)) *ShellRunnerI_ExecGitCommand_Call {
	_c.Call.Return(run)
	return _c
}
