// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	bytes "bytes"
	exec "os/exec"

	mock "github.com/stretchr/testify/mock"
)

// ShellRunnerI is an autogenerated mock type for the ShellRunnerI type
type ShellRunnerI struct {
	mock.Mock
}

// ExecGitCommand provides a mock function with given fields: args, stdoutb, erroutb, dir
func (_m *ShellRunnerI) ExecGitCommand(args []string, stdoutb *bytes.Buffer, erroutb *bytes.Buffer, dir string) (*exec.Cmd, error) {
	ret := _m.Called(args, stdoutb, erroutb, dir)

	var r0 *exec.Cmd
	if rf, ok := ret.Get(0).(func([]string, *bytes.Buffer, *bytes.Buffer, string) *exec.Cmd); ok {
		r0 = rf(args, stdoutb, erroutb, dir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*exec.Cmd)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string, *bytes.Buffer, *bytes.Buffer, string) error); ok {
		r1 = rf(args, stdoutb, erroutb, dir)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
