# UPDATE_HERE
name: build-git-get

on: [push]

permissions:
  contents: write

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: "1.18.3"
      id: go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.9.2
        install-only: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check out full code history
      run: |
        git fetch --prune --unshallow
        git pull --tags

    - name: Test and Build
      run: |
        make

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: "1.18"
      id: go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: v1.7.0
        install-only: true

    - name: Install svu
      run: |
        curl -L https://github.com/caarlos0/svu/releases/download/v1.9.0/svu_1.9.0_linux_amd64.tar.gz | sudo tar -C /usr/local/bin/ -xz -f - svu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check out full code history
      run: |
        git fetch --prune --unshallow
        git pull --tags

    - name: Test and Build
      run: |
        make

    - name: Release
      shell: bash
      run: |
        git tag "$(svu next)"
        git push --tags
        goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
