# UPDATE_HERE
name: build-git-get

on: [push]

permissions:
  contents: write

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.4"
      id: go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: v1.22.1
        install-only: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check out full code history
      run: |
        git fetch --prune --unshallow
        git pull --tags

    - name: Test and Build
      run: |
        make

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message # commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.21.4"
      id: go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: v1.22.1
        install-only: true

    - name: Install svu
      run: |
        # https://github.com/caarlos0/svu/releases
        curl -L https://github.com/caarlos0/svu/releases/download/v1.11.0/svu_1.11.0_linux_amd64.tar.gz | sudo tar -C /usr/local/bin/ -xz -f - svu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Check out full code history
      run: |
        git fetch --prune --unshallow
        git pull --tags

    - name: Test and Build
      run: |
        make

    - name: Release
      shell: bash
      run: |
        git tag "$(svu next)"
        git push --tags
        goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      if: always()
      with:
        status: ${{ job.status }}
        fields: repo,message # commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
