# UPDATE_HERE
name: build-git-get
on: [push]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:

    - name: Set up Go 17.17.6
      uses: actions/setup-go@v1
      with:
        go-version: 17.17.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        make

  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:

    - name: Set up Go 17.17.6
      uses: actions/setup-go@v1
      with:
        go-version: 17.17.6
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Check out full code history
      run: |
        git fetch --prune --unshallow
        git pull --tags

    - name: Build and Test
      run: |
        make

    - name: Run hub release
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        curl -LO https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_386
        mv git-chglog_linux_386 bin/git-chglog
        chmod +x bin/git-chglog
        #go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
        export PATH=$( pwd )/bin:$PATH
        git config --global user.email "isindir@users.sf.net"
        git config --global user.name "Eriks Zelenka"
        make release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
