name: reviewdog
on: [pull_request]

jobs:
  reviewdog:
    name: linters
    runs-on: ubuntu-latest
    steps:
      # UPDATE_HERE
      # https://github.com/actions/checkout/releases
      - name: check out code into the go module directory
        uses: actions/checkout@v4


      # UPDATE_HERE
      # https://github.com/reviewdog/action-golangci-lint/releases
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        # with:
        #   golangci_lint_flags: "--timeout=15m"

      # UPDATE_HERE
      # https://github.com/reviewdog/action-actionlint/releases
      - name: action-lint
        uses: reviewdog/action-actionlint@v1
